spring.application.name=hoian-cooking

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hoian_cooking
spring.datasource.username=postgres
spring.datasource.password=12341234
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:ds6fxaiqd}
cloudinary.api-key=${CLOUDINARY_API_KEY:131272294536855}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:8yOP2BkLtGeYFjULYEk59IWjZrA}
